import React from "react";
                 import PopQuiz, {PopQuizItem} from './PopQuiz.jsx'
                 import ProofWalkthru from './ProofWalkthru.jsx'
                 
                const Chapter4 = ({bullet}) => {
                    return (
                        <div>
                        <hr></hr><h4 className="header1" id="computing-the-partial-derivative">computing the partial derivative</h4>
<div className="text textcolor">In order to compute the partial derivative: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo><mi>l</mi></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><mo>&#x0003D;</mo><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><mo stretchy="false">&#x00028;</mo><mo>&#x02212;</mo><mi>log</mi><mspace width="0.222em" /><msub><mi>&#x003C3;</mi><mi>y</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mo stretchy="false">&#x00029;</mo></mrow></math></div>
 which involves the softmax function <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>y</mi></msub></mrow></math>, we first need to know how to compute partial derivatives of softmax. The following theorem tells us how.</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">theorem</span><br/><br/> For the (single-component) softmax function: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><msub><mi>z</mi><mn>1</mn></msub></mtd></mtr><mtr><mtd><mo>&#x022EE;</mo></mtd></mtr><mtr><mtd><msub><mi>z</mi><mi>C</mi></msub></mtd></mtr></mtable><mo>&#x0005D;</mo><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow><mo>&#x0003D;</mo><mfrac><mrow><mi>exp</mi><mo stretchy="false">&#x00028;</mo><msub><mi>z</mi><mi>j</mi></msub><mo stretchy="false">&#x00029;</mo></mrow><mrow><munderover><mo>&#x02211;</mo><mrow><mi>c</mi><mo>&#x0003D;</mo><mn>1</mn></mrow><mi>C</mi></munderover><mi>exp</mi><mo stretchy="false">&#x00028;</mo><msub><mi>z</mi><mi>c</mi></msub><mo stretchy="false">&#x00029;</mo></mrow></mfrac></mrow></math></div>
 where <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>1</mn><mo>&#x02264;</mo><mi>j</mi><mo>&#x02264;</mo><mi>C</mi></mrow></math>, the partial derivative <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><msub><mrow><mi mathvariant="script">&#x003C3;</mi></mrow><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo></mrow></math> is: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><msub><mrow><mi mathvariant="script">&#x003C3;</mi></mrow><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mo stretchy="false">&#x00028;</mo><mrow><mn mathvariant="double-struck">1</mn></mrow><mo stretchy="false">&#x00028;</mo><mi>i</mi><mo>&#x0003D;</mo><mi>j</mi><mo stretchy="false">&#x00029;</mo><mo>&#x02212;</mo><msub><mi>&#x003C3;</mi><mi>i</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mo stretchy="false">&#x00029;</mo></mrow></math></div>
 </div>
</div>
<div className="text textcolor"><ProofWalkthru><div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo></mrow></math></div>
 <div className="justification">...</div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><mi>log</mi><mspace width="0.222em" /><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo></mrow></math></div>
 <div className="justification">because: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><mi>log</mi><mspace width="0.222em" /><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo></mrow></mfrac><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo></mrow></math></div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><mi>log</mi><mspace width="0.222em" /><mrow><mfrac><mrow><msup><mi className="proof-highlight" mathvariant="bold">e</mi><mrow><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">j</mi></msub></mrow></msup></mrow><mrow><munderover><mo className="proof-highlight" mathvariant="bold">&#x02211;</mo><mrow><mi className="proof-highlight" mathvariant="bold">c</mi><mo className="proof-highlight" mathvariant="bold">&#x0003D;</mo><mn className="proof-highlight" mathvariant="bold">1</mn></mrow><mi className="proof-highlight" mathvariant="bold">C</mi></munderover><msup><mi className="proof-highlight" mathvariant="bold">e</mi><mrow><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">c</mi></msub></mrow></msup></mrow></mfrac></mrow></mrow></math></div>
 <div className="justification">by the definition of softmax</div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mrow><mi className="proof-highlight" mathvariant="bold">log</mi><mspace width="0.222em" /><msup><mi className="proof-highlight" mathvariant="bold">e</mi><mrow><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">j</mi></msub></mrow></msup><mo className="proof-highlight" mathvariant="bold">&#x02212;</mo><mi className="proof-highlight" mathvariant="bold">log</mi><mspace width="0.222em" /><munderover><mo className="proof-highlight" mathvariant="bold">&#x02211;</mo><mrow><mi className="proof-highlight" mathvariant="bold">c</mi><mo className="proof-highlight" mathvariant="bold">&#x0003D;</mo><mn className="proof-highlight" mathvariant="bold">1</mn></mrow><mi className="proof-highlight" mathvariant="bold">C</mi></munderover><msup><mi className="proof-highlight" mathvariant="bold">e</mi><mrow><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">c</mi></msub></mrow></msup></mrow><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">because: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>log</mi><mspace width="0.222em" /><mfrac><mrow><mi>x</mi></mrow><mrow><mi>y</mi></mrow></mfrac><mo>&#x0003D;</mo><mi>log</mi><mspace width="0.222em" /><mi>x</mi><mo>&#x02212;</mo><mi>log</mi><mspace width="0.222em" /><mi>y</mi></mrow></math></div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mrow><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">j</mi></msub></mrow><mo>&#x02212;</mo><mi>log</mi><mspace width="0.222em" /><munderover><mo>&#x02211;</mo><mrow><mi>c</mi><mo>&#x0003D;</mo><mn>1</mn></mrow><mi>C</mi></munderover><msup><mi>e</mi><mrow><msub><mi>z</mi><mi>c</mi></msub></mrow></msup><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">because: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>log</mi><mspace width="0.222em" /><msup><mi>e</mi><mi>x</mi></msup><mo>&#x0003D;</mo><mi>x</mi></mrow></math></div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mrow><mfrac><mrow><mo className="proof-highlight" mathvariant="bold">&#x02202;</mo></mrow><mrow><mo className="proof-highlight" mathvariant="bold">&#x02202;</mo><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">i</mi></msub></mrow></mfrac></mrow><msub><mi>z</mi><mi>j</mi></msub><mo>&#x02212;</mo><mrow><mfrac><mrow><mo className="proof-highlight" mathvariant="bold">&#x02202;</mo></mrow><mrow><mo className="proof-highlight" mathvariant="bold">&#x02202;</mo><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">i</mi></msub></mrow></mfrac></mrow><mi>log</mi><mspace width="0.222em" /><munderover><mo>&#x02211;</mo><mrow><mi>c</mi><mo>&#x0003D;</mo><mn>1</mn></mrow><mi>C</mi></munderover><msup><mi>e</mi><mrow><msub><mi>z</mi><mi>c</mi></msub></mrow></msup><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">because: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><mi>x</mi></mrow></mfrac><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0002B;</mo><mi>g</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><mi>x</mi></mrow></mfrac><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0002B;</mo><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><mi>x</mi></mrow></mfrac><mi>g</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo></mrow></math></div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mrow><mn className="proof-highlight" mathvariant="bold">1</mn><mo stretchy="false">&#x00028;</mo><mi className="proof-highlight" mathvariant="bold">i</mi><mo className="proof-highlight" mathvariant="bold">&#x0003D;</mo><mi className="proof-highlight" mathvariant="bold">j</mi><mo stretchy="false">&#x00029;</mo></mrow><mo>&#x02212;</mo><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><mi>log</mi><mspace width="0.222em" /><munderover><mo>&#x02211;</mo><mrow><mi>c</mi><mo>&#x0003D;</mo><mn>1</mn></mrow><mi>C</mi></munderover><msup><mi>e</mi><mrow><msub><mi>z</mi><mi>c</mi></msub></mrow></msup><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">because: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><msub><mi>z</mi><mi>j</mi></msub><mo>&#x0003D;</mo><mn>1</mn></mrow></math> if <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>i</mi><mo>&#x0003D;</mo><mi>j</mi></mrow></math>; <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><msub><mi>z</mi><mi>j</mi></msub><mo>&#x0003D;</mo><mn>0</mn></mrow></math> if <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>i</mi><mo>&#x02260;</mo><mi>j</mi></mrow></math></div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mrow><mn mathvariant="double-struck">1</mn></mrow><mo stretchy="false">&#x00028;</mo><mi>i</mi><mo>&#x0003D;</mo><mi>j</mi><mo stretchy="false">&#x00029;</mo><mo>&#x02212;</mo><mrow><mfrac><mrow><mn className="proof-highlight" mathvariant="bold">1</mn></mrow><mrow><munderover><mo className="proof-highlight" mathvariant="bold">&#x02211;</mo><mrow><mi className="proof-highlight" mathvariant="bold">c</mi><mo className="proof-highlight" mathvariant="bold">&#x0003D;</mo><mn className="proof-highlight" mathvariant="bold">1</mn></mrow><mi className="proof-highlight" mathvariant="bold">C</mi></munderover><msup><mi className="proof-highlight" mathvariant="bold">e</mi><mrow><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">c</mi></msub></mrow></msup></mrow></mfrac><mfrac><mrow><mo className="proof-highlight" mathvariant="bold">&#x02202;</mo></mrow><mrow><mo className="proof-highlight" mathvariant="bold">&#x02202;</mo><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">i</mi></msub></mrow></mfrac><munderover><mo className="proof-highlight" mathvariant="bold">&#x02211;</mo><mrow><mi className="proof-highlight" mathvariant="bold">c</mi><mo className="proof-highlight" mathvariant="bold">&#x0003D;</mo><mn className="proof-highlight" mathvariant="bold">1</mn></mrow><mi className="proof-highlight" mathvariant="bold">C</mi></munderover><msup><mi className="proof-highlight" mathvariant="bold">e</mi><mrow><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">c</mi></msub></mrow></msup></mrow><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">because: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><mi>x</mi></mrow></mfrac><mi>log</mi><mspace width="0.222em" /><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo></mrow></mfrac><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><mi>x</mi></mrow></mfrac><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo></mrow></math></div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mrow><mn mathvariant="double-struck">1</mn></mrow><mo stretchy="false">&#x00028;</mo><mi>i</mi><mo>&#x0003D;</mo><mi>j</mi><mo stretchy="false">&#x00029;</mo><mo>&#x02212;</mo><mfrac><mrow><mrow><msup><mi className="proof-highlight" mathvariant="bold">e</mi><mrow><msub><mi className="proof-highlight" mathvariant="bold">z</mi><mi className="proof-highlight" mathvariant="bold">i</mi></msub></mrow></msup></mrow></mrow><mrow><munderover><mo>&#x02211;</mo><mrow><mi>c</mi><mo>&#x0003D;</mo><mn>1</mn></mrow><mi>C</mi></munderover><msup><mi>e</mi><mrow><msub><mi>z</mi><mi>c</mi></msub></mrow></msup></mrow></mfrac><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">because: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mo>&#x02202;</mo></mrow><mrow><mo>&#x02202;</mo><msub><mi>z</mi><mi>i</mi></msub></mrow></mfrac><munderover><mo>&#x02211;</mo><mrow><mi>c</mi><mo>&#x0003D;</mo><mn>1</mn></mrow><mi>C</mi></munderover><msup><mi>e</mi><mrow><msub><mi>z</mi><mi>c</mi></msub></mrow></msup><mo>&#x0003D;</mo><msup><mi>e</mi><mrow><msub><mi>z</mi><mi>i</mi></msub></mrow></msup></mrow></math></div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>&#x003C3;</mi><mi>j</mi></msub><mo stretchy="false">&#x00028;</mo><mi>z</mi><mo stretchy="false">&#x00029;</mo><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mrow><mn mathvariant="double-struck">1</mn></mrow><mo stretchy="false">&#x00028;</mo><mi>i</mi><mo>&#x0003D;</mo><mi>j</mi><mo stretchy="false">&#x00029;</mo><mo>&#x02212;</mo><mrow><msub><mi className="proof-highlight" mathvariant="bold">&#x003C3;</mi><mi className="proof-highlight" mathvariant="bold">i</mi></msub><mo stretchy="false">&#x00028;</mo><mi className="proof-highlight" mathvariant="bold">z</mi><mo stretchy="false">&#x00029;</mo></mrow><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">by the definition of softmax</div></div></ProofWalkthru>
</div>

                        </div>
                    );
                }
    

                export default Chapter4;
                
