import React from "react";
                 import PopQuiz, {PopQuizItem} from './PopQuiz.jsx'
                 import ProofWalkthru from './ProofWalkthru.jsx'
                 
                const Chapter1 = ({bullet}) => {
                    return (
                        <div>
                        <hr></hr><h4 className="header1" id="variables">variables</h4>
<div className="text textcolor">Variables are such a central part of a mathematics education that one might wonder: why even bother reviewing them? But deep neural networks conscript so many variables into service that it helps to have formalisms for keeping them straight. </div>
<div className="text textcolor">A <span className="term">variable</span> is a symbol associated with a <span className="term">domain</span> of possible values. We will usually use capital (English and Greek) letters to represent variables, and we will assume that we can apply a global function <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x00394;</mi></mrow></math> to any variable to obtain its domain.  Domains can be <span className="term">discrete</span> (a &quot;countable&quot; set of distinct values, which can be <span className="term">finite</span> or <span className="term">infinite</span>) or <span className="term">continuous</span> (like the set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0211D;</mi></mrow></math> of all real numbers), depending on our needs. </div>
<div className="text textcolor"><img className="image" src="boards/board-vars1.png" alt="Examples of variables" /></div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> To represent the current season, we could use a variable <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>S</mi></mrow></math> with the <span className="term">finite discrete</span> domain: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x00394;</mi><mo stretchy="false">&#x00028;</mo><mi>S</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mi>&#x0007B;</mi><mtext mathvariant="monospace">winter</mtext><mo>&#x0002C;</mo><mtext mathvariant="monospace">spring</mtext><mo>&#x0002C;</mo><mtext mathvariant="monospace">summer</mtext><mo>&#x0002C;</mo><mtext mathvariant="monospace">autumn</mtext><mi>&#x0007D;</mi></mrow></math></div>
 To represent the current year, we could use a variable <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>Y</mi></mrow></math> with the <span className="term">infinite discrete</span> domain: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x00394;</mi><mo stretchy="false">&#x00028;</mo><mi>Y</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mi>&#x0007B;</mi><mi>&#x02026;</mi><mo>&#x0002C;</mo><mn>2018</mn><mo>&#x0002C;</mo><mn>2019</mn><mo>&#x0002C;</mo><mn>2020</mn><mo>&#x0002C;</mo><mn>2021</mn><mo>&#x0002C;</mo><mn>2022</mn><mo>&#x0002C;</mo><mi>&#x02026;</mi><mi>&#x0007D;</mi></mrow></math></div>
 To represent the current outdoor temperature, we could use a variable <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>T</mi></mrow></math> with <span className="term">continuous</span> domain: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x00394;</mi><mo stretchy="false">&#x00028;</mo><mi>T</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mi>&#x0211D;</mi></mrow></math></div>
 </div>
</div>
<div className="text textcolor">One important discrete domain is the <span className="term">binary domain</span> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mn>0</mn><mo>&#x0002C;</mo><mn>1</mn><mi>&#x0007D;</mi></mrow></math>. A variable <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi></mrow></math> with domain <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mn>0</mn><mo>&#x0002C;</mo><mn>1</mn><mi>&#x0007D;</mi></mrow></math> is referred to as a <span className="term">binary variable</span>. Binary variables are often interpreted as <span className="term">booleans</span>, where the value <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>1</mn></mrow></math> corresponds to <span className="term">true</span> and the value <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>0</mn></mrow></math> corresponds to <span className="term">false</span>. 	</div>
<div className="text textcolor">In deep learning, variables are often collected together into <span className="term">sets</span>, and it helps to have notation for dealing with these variable sets. As with variables, we will usually use capital letters to refer to a variable set, but will often add subscripts to distinguish the components, e.g. </div>
<div className="text textcolor"><div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi><mo>&#x0003D;</mo><mi>&#x0007B;</mi><msub><mi>X</mi><mn>1</mn></msub><mo>&#x0002C;</mo><mo>&#x02026;</mo><mo>&#x0002C;</mo><msub><mi>X</mi><mi>n</mi></msub><mi>&#x0007D;</mi></mrow></math></div>
</div>
<div className="text textcolor">We can extend the idea of the <span className="term">value of a variable</span> (e.g. &quot;winter&quot; is a value of variable <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>S</mi></mrow></math> that we defined above) to the <span className="term">value of a variable set</span>, which we will call an <span className="term">event</span>.</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Definition</span><br/><br/>Define an <span className="term">event</span> of variable set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi><mo>&#x0003D;</mo><mi>&#x0007B;</mi><msub><mi>X</mi><mn>1</mn></msub><mo>&#x0002C;</mo><mo>&#x02026;</mo><mo>&#x0002C;</mo><msub><mi>X</mi><mi>n</mi></msub><mi>&#x0007D;</mi></mrow></math> as a function that maps each variable in set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi></mrow></math> to a value in its domain <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x00394;</mi><mo stretchy="false">&#x00028;</mo><mi>X</mi><mo stretchy="false">&#x00029;</mo></mrow></math>.</div>
</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> Assume <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>S</mi></mrow></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>Y</mi></mrow></math> are the example variables defined above. For variable set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>V</mi><mo>&#x0003D;</mo><mi>&#x0007B;</mi><mi>S</mi><mo>&#x0002C;</mo><mi>Y</mi><mi>&#x0007D;</mi></mrow></math> , one event is: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mi>S</mi><mo>&#x021A6;</mo><mtext mathvariant="monospace">summer</mtext><mo>&#x0002C;</mo><mi>Y</mi><mo>&#x021A6;</mo><mn>1969</mn><mi>&#x0007D;</mi></mrow></math></div>
 If you're unfamiliar with this way of representing a function, it says: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>S</mi></mrow></math> maps to &quot;summer&quot; and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>Y</mi></mrow></math> maps to 1969. </div>
</div>
<div className="text textcolor">To refer to an event, we will usually use the <span className="term">lowercase</span> version of the letter that represents its variable set. For instance, we would use <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>x</mi></mrow></math> to refer to an event of variable set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi></mrow></math>. Because an event <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>x</mi></mrow></math> of variable set</div>
<div className="text textcolor"><div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi><mo>&#x0003D;</mo><mi>&#x0007B;</mi><msub><mi>X</mi><mn>1</mn></msub><mo>&#x0002C;</mo><mo>&#x02026;</mo><mo>&#x0002C;</mo><msub><mi>X</mi><mi>n</mi></msub><mi>&#x0007D;</mi></mrow></math></div>
</div>
<div className="text textcolor">is a <span className="term">function</span>, we can refer to the value of a particular variable <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>X</mi><mi>i</mi></msub><mo>&#x02208;</mo><mi>X</mi></mrow></math> using this notation:</div>
<div className="text textcolor"><div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>x</mi><mo stretchy="false">&#x00028;</mo><msub><mi>X</mi><mi>i</mi></msub><mo stretchy="false">&#x00029;</mo></mrow></math></div>
</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> Consider the event: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>v</mi><mo>&#x0003D;</mo><mi>&#x0007B;</mi><mi>S</mi><mo>&#x021A6;</mo><mtext mathvariant="monospace">summer</mtext><mo>&#x0002C;</mo><mi>Y</mi><mo>&#x021A6;</mo><mn>1969</mn><mi>&#x0007D;</mi></mrow></math></div>
 Then <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>v</mi><mo stretchy="false">&#x00028;</mo><mi>S</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mtext mathvariant="monospace">summer</mtext></mrow></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>v</mi><mo stretchy="false">&#x00028;</mo><mi>Y</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mn>1969</mn></mrow></math>. </div>
</div>
<div className="text textcolor">It will sometimes be convenient to have a more compact notation for events.  To refer to an arbitrary event <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><msub><mi>X</mi><mn>1</mn></msub><mo>&#x021A6;</mo><msub><mi>x</mi><mn>1</mn></msub><mo>&#x0002C;</mo><msub><mi>X</mi><mn>2</mn></msub><mo>&#x021A6;</mo><msub><mi>x</mi><mn>2</mn></msub><mo>&#x0002C;</mo><mo>&#x02026;</mo><mo>&#x0002C;</mo><msub><mi>X</mi><mi>n</mi></msub><mo>&#x021A6;</mo><msub><mi>x</mi><mi>n</mi></msub><mi>&#x0007D;</mi></mrow></math></div>
 of a variable set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><msub><mi>X</mi><mn>1</mn></msub><mo>&#x0002C;</mo><msub><mi>X</mi><mn>2</mn></msub><mo>&#x0002C;</mo><mo>&#x02026;</mo><mo>&#x0002C;</mo><msub><mi>X</mi><mi>n</mi></msub><mi>&#x0007D;</mi></mrow></math>, we will sometimes just use the concatenation <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>x</mi><mn>1</mn></msub><msub><mi>x</mi><mn>2</mn></msub><mo>&#x0002E;</mo><mo>&#x0002E;</mo><mo>&#x0002E;</mo><msub><mi>x</mi><mi>n</mi></msub></mrow></math>. Similarly, given two events <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>v</mi><mo>&#x02208;</mo><mi>&#x00394;</mi><mo stretchy="false">&#x00028;</mo><mi>V</mi><mo stretchy="false">&#x00029;</mo></mrow></math>,  <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>w</mi><mo>&#x02208;</mo><mi>&#x00394;</mi><mo stretchy="false">&#x00028;</mo><mi>W</mi><mo stretchy="false">&#x00029;</mo></mrow></math> of disjoint variable sets <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>V</mi></mrow></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>W</mi></mrow></math>, we will use the concatenation <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>v</mi><mi>w</mi></mrow></math> to refer to the union <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>v</mi><mo>&#x0222A;</mo><mi>w</mi></mrow></math> of the events.</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> In a proof, we might state: &quot;Let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>s</mi><mi>y</mi></mrow></math> be an event of variable set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mi>S</mi><mo>&#x0002C;</mo><mi>Y</mi><mi>&#x0007D;</mi></mrow></math>.&quot;  In this context, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>s</mi><mi>y</mi></mrow></math> is a shorthand for: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mi>S</mi><mo>&#x021A6;</mo><mi>s</mi><mo>&#x0002C;</mo><mi>Y</mi><mo>&#x021A6;</mo><mi>y</mi><mi>&#x0007D;</mi></mrow></math></div>
 </div>
</div>
<div className="text textcolor">Finally, define the <span className="term">domain</span> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x00394;</mi><mo stretchy="false">&#x00028;</mo><mi>X</mi><mo stretchy="false">&#x00029;</mo></mrow></math> of variable set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi><mo>&#x0003D;</mo><mi>&#x0007B;</mi><msub><mi>X</mi><mn>1</mn></msub><mo>&#x0002C;</mo><mo>&#x02026;</mo><mo>&#x0002C;</mo><msub><mi>X</mi><mi>n</mi></msub><mi>&#x0007D;</mi></mrow></math> as the set of all possible events of <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi></mrow></math>.</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> Domain <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x00394;</mi><mo stretchy="false">&#x00028;</mo><mrow><mi>S</mi><mo>&#x0002C;</mo><mi>Y</mi></mrow><mo stretchy="false">&#x00029;</mo></mrow></math> contains the following events (among infinitely many others): <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mi>S</mi><mo>&#x021A6;</mo><mtext mathvariant="monospace">summer</mtext><mo>&#x0002C;</mo><mi>Y</mi><mo>&#x021A6;</mo><mn>1969</mn><mi>&#x0007D;</mi></mrow></math></div>
 <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mi>S</mi><mo>&#x021A6;</mo><mtext mathvariant="monospace">winter</mtext><mo>&#x0002C;</mo><mi>Y</mi><mo>&#x021A6;</mo><mn>1709</mn><mi>&#x0007D;</mi></mrow></math></div>
 <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mi>S</mi><mo>&#x021A6;</mo><mtext mathvariant="monospace">spring</mtext><mo>&#x0002C;</mo><mi>Y</mi><mo>&#x021A6;</mo><mn>2020</mn><mi>&#x0007D;</mi></mrow></math></div>
 </div>
</div>
<hr></hr><h4 className="header1" id="pop-quiz">pop quiz</h4>
<div className="text textcolor"><PopQuiz>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> If we have three variables <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi></mrow></math>, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>C</mi></mrow></math>, each with domain of size 4, what is the size of the domain of the variable set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>&#x0007B;</mi><mi>A</mi><mo>&#x0002C;</mo><mi>B</mi><mo>&#x0002C;</mo><mi>C</mi><mi>&#x0007D;</mi></mrow></math>? </div>
 <div className="pop-answer"> If variables <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi></mrow></math>, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>, and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>C</mi></mrow></math> each have a domain of size 4, the size of the combined domain of the variables <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi></mrow></math>, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>, and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>C</mi></mrow></math> is the product of the sizes of their individual domains, i.e.: <div className="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>4</mn><mo>&#x0002A;</mo><mn>4</mn><mo>&#x0002A;</mo><mn>4</mn><mo>&#x0003D;</mo><mn>64</mn></mrow></math></div>
 </div>
 </PopQuizItem>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> Give a real-world example of a continuous value. </div>
 <div className="pop-answer"> A real-world example of a continuous variable is temperature. Temperature can take on any value within a given range and is not restricted to specific, separate values. For instance, the temperature in a city can be 72.3 degrees Fahrenheit, 72.31 degrees Fahrenheit, 72.314 degrees Fahrenheit, and so on, with the value changing continuously and smoothly over time. </div>
 </PopQuizItem>
 </PopQuiz>
     </div>

                        </div>
                    );
                }
    

                export default Chapter1;
                
