import React from "react";
                 import Equation from './Equation.jsx'
                 import ColorPicker from './ColorPicker.jsx'
                 import PopQuiz, {PopQuizItem} from './PopQuiz.jsx'
                 import ProofWalkthru from './ProofWalkthru.jsx'
                 import GradientDescentDemo from './GradientDescentDemo.jsx';
                 import FollowTheFold from './FollowTheFold.jsx';
                 import ContourExplorer from './ContourExplorer.jsx';
                 import Prologue from './Prologue.jsx';
                 import MatrixMultiplication from './MatrixMultiplication.jsx';
                 
                const Chapter1 = ({bullet, color1, color2, color3}) => {
                    return (
                        <div>
                        <div className="text textcolor"><Prologue title="mathematical foundations" image="images/blackboard.png" intro1="Without mathematics, there’s nothing you can do. Everything around you is mathematics. Everything around you is numbers. 「Shakuntala Devi」" intro2="One, two, three, four, tell me that you love me more.「Feist」" intro3="You can't kick ass if you can't kick.
「Some contestant on season one of Race To Survive: Alaska. They didn't win.」" />
</div>
<div className="header-padding" /><hr></hr><h4 className="header1" id="vectors">vectors</h4>
<div className="text textcolor">A <span className="term">vector</span> is an array of numbers, which we will represent like this:</div>
<div className="text textcolor"><Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mo>&#x00028;</mo><mtable><mtr><mtd><mn>1.5</mn></mtd></mtr><mtr><mtd><mo>&#x02212;</mo><mn>2</mn></mtd></mtr><mtr><mtd><mn>50</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math></Equation>
</div>
<div className="text textcolor">We will adopt the convention of using parentheses (as above) to delimit vectors. When using a variable to represent a vector, we will typically use upper-case letters, e.g.:</div>
<div className="text textcolor"><Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mn>1.5</mn></mtd></mtr><mtr><mtd><mo>&#x02212;</mo><mn>2</mn></mtd></mtr><mtr><mtd><mn>50</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math></Equation>
</div>
<div className="text textcolor">Moreover, we will use subscripts to represent individual elements of a vector, e.g.:</div>
<div className="text textcolor"><Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><msub><mi>A</mi><mn>1</mn></msub></mtd></mtr><mtr><mtd><msub><mi>A</mi><mn>2</mn></msub></mtd></mtr><mtr><mtd><msub><mi>A</mi><mn>3</mn></msub></mtd></mtr></mtable><mo>&#x00029;</mo><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mn>1.5</mn></mtd></mtr><mtr><mtd><mo>&#x02212;</mo><mn>2</mn></mtd></mtr><mtr><mtd><mn>50</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math></Equation>
</div>
<div className="text textcolor">The number of elements in a vector is referred to as the <span className="term">length</span> of the vector. For instance, the above example has length 3.</div>
<div className="text textcolor">In deep learning, vectors are used extensively to organize related quantities. We will often use them to compute <span className="term">weighted sums</span> using the <span className="term">dot product</span> operator. </div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Definition</span><br/><br/> Let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><msub><mi>A</mi><mn>1</mn></msub></mtd></mtr><mtr><mtd><mo>&#x022EE;</mo></mtd></mtr><mtr><mtd><msub><mi>A</mi><mi>n</mi></msub></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><msub><mi>B</mi><mn>1</mn></msub></mtd></mtr><mtr><mtd><mo>&#x022EE;</mo></mtd></mtr><mtr><mtd><msub><mi>B</mi><mi>n</mi></msub></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math> be vectors of length <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>n</mi></mrow></math>. The <span className="term">dot product</span> operator is defined: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>&#x000B7;</mi><mi>B</mi><mo>&#x0003D;</mo><msub><mi>A</mi><mn>1</mn></msub><msub><mi>B</mi><mn>1</mn></msub><mo>&#x0002B;</mo><mo>&#x02026;</mo><mo>&#x0002B;</mo><msub><mi>A</mi><mi>n</mi></msub><msub><mi>B</mi><mi>n</mi></msub></mrow></math></Equation>
 </div>
</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> For instance, suppose you taking a course whose grade breakdown was 20% homework, 30% midterm, and 50% final exam. If your homework score was 90/100, your midterm score was 80/100, and your final exam score was 70/100, then your overall score would be the following weighted sum: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>.20</mi><mi>&#x000D7;</mi><mn>90</mn><mo>&#x0002B;</mo><mi>.30</mi><mi>&#x000D7;</mi><mn>80</mn><mo>&#x0002B;</mo><mi>.50</mi><mi>&#x000D7;</mi><mn>70</mn><mo>&#x0003D;</mo><mn>77</mn></mrow></math></Equation>
 Another way to express this weighted sum is to collect the percentages and the scores into two separate vectors: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.20</mi></mtd></mtr><mtr><mtd><mi>.30</mi></mtd></mtr><mtr><mtd><mi>.50</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mstyle displaystyle="false" scriptlevel="0"><mtext>&#x000A0;and&#x000A0;</mtext></mstyle><mi>B</mi><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>80</mn></mtd></mtr><mtr><mtd><mn>70</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math></Equation>
 Then the weighted sum can be expressed using the <span className="term">dot product</span> operator: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>&#x000B7;</mi><mi>B</mi><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.20</mi></mtd></mtr><mtr><mtd><mi>.30</mi></mtd></mtr><mtr><mtd><mi>.50</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mi>&#x000B7;</mi><mo>&#x00028;</mo><mtable><mtr><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>80</mn></mtd></mtr><mtr><mtd><mn>70</mn></mtd></mtr></mtable><mo>&#x00029;</mo><mo>&#x0003D;</mo><mi>.20</mi><mi>&#x000D7;</mi><mn>90</mn><mo>&#x0002B;</mo><mi>.30</mi><mi>&#x000D7;</mi><mn>80</mn><mo>&#x0002B;</mo><mi>.50</mi><mi>&#x000D7;</mi><mn>70</mn><mo>&#x0003D;</mo><mn>77</mn></mrow></math></Equation>
 </div>
</div>
<div className="header-padding" /><hr></hr><h4 className="header1" id="matrices">matrices</h4>
<div className="text textcolor">Sometimes we need to compute lots of similar weighted sums. Imagine that we didn't just want to compute the final grade of one student, but rather the final grades of several students.</div>
<div className="text textcolor">Here's how each student performed in the course:</div>
<div className="text textcolor"><img className="image" src="boards/board-matrices1.jpg" alt="Course grades" /></div>
<div className="text textcolor">As before, the course has the following grade breakdown:</div>
<ul>
<li><div className="text textcolor">20% homework</div>
</li>
<li><div className="text textcolor">30% midterm</div>
</li>
<li><div className="text textcolor">50% final exam</div>
</li>
</ul>
<div className="text textcolor">But there's also an alternative grade breakdown for students who perform better on the final exam than on the midterm. In that case, they can opt for the following grade breakdown:</div>
<ul>
<li><div className="text textcolor">20% homework</div>
</li>
<li><div className="text textcolor">0% midterm</div>
</li>
<li><div className="text textcolor">80% final exam</div>
</li>
</ul>
<div className="text textcolor">Each student's final grade according to each grade breakdown can be calculated by computing six similar dot products:</div>
<div className="text textcolor"><img className="image" src="boards/board-matrices2.jpg" alt="Final grade computation" /></div>
<div className="text textcolor">For instance, the top-left box computes the final grade of the first student according to the first grade breakdown:</div>
<div className="text textcolor"><Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mi>.3</mi></mtd></mtr><mtr><mtd><mi>.5</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mi>&#x000B7;</mi><mo>&#x00028;</mo><mtable><mtr><mtd><mn>80</mn></mtd></mtr><mtr><mtd><mn>95</mn></mtd></mtr><mtr><mtd><mn>90</mn></mtd></mtr></mtable><mo>&#x00029;</mo><mo>&#x0003D;</mo><mi>.2</mi><mi>&#x000D7;</mi><mn>80</mn><mo>&#x0002B;</mo><mi>.3</mi><mi>&#x000D7;</mi><mn>95</mn><mo>&#x0002B;</mo><mi>.5</mi><mi>&#x000D7;</mi><mn>90</mn><mo>&#x0003D;</mo><mn>89.5</mn></mrow></math></Equation>
</div>
<div className="text textcolor">We can express the above grid of computations more compactly by flipping the grade breakdown vectors on their side and performing a <span className="term">matrix multiplication</span>:</div>
<div className="text textcolor"><img className="image" src="boards/board-matrices3.jpg" alt="Final grade computation as matrix multiplication" /></div>
<div className="text textcolor">This is a general technique that will be central to our study of deep learning, so let's formalize these ideas.</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Definition</span><br/><br/> A <span className="term">matrix</span> is a two-dimensional array of numbers. </div>
</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> The matrices from our grade breakdown example can be defined: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mi>.2</mi></mtd><mtd><mi>.3</mi></mtd><mtd><mi>.5</mi></mtd></mtr><mtr><mtd><mi>.2</mi></mtd><mtd><mn>0</mn></mtd><mtd><mi>.8</mi></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math></Equation>
 <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>80</mn></mtd><mtd><mn>90</mn></mtd><mtd><mn>96</mn></mtd></mtr><mtr><mtd><mn>95</mn></mtd><mtd><mn>80</mn></mtd><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>90</mn></mtd><mtd><mn>70</mn></mtd><mtd><mn>92</mn></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math></Equation>
 Since matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi></mrow></math> has 2 rows and 3 columns, it can be referred to as a <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>2</mn><mi>&#x000D7;</mi><mn>3</mn></mrow></math> matrix, or we can say that it has <span className="term">shape</span> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mo stretchy="false">&#x00028;</mo><mn>2</mn><mo>&#x0002C;</mo><mn>3</mn><mo stretchy="false">&#x00029;</mo></mrow></math>. We will adopt the convention of using square brackets (as above) to denote matrices. </div>
</div>
<div className="text textcolor"><PopQuiz>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> What is the shape of matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>? </div>
 <div className="pop-answer"> Since matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math> has 3 rows and 3 columns, it is a 3x3 matrix. In other words, it has shape <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mo stretchy="false">&#x00028;</mo><mn>3</mn><mo>&#x0002C;</mo><mn>3</mn><mo stretchy="false">&#x00029;</mo></mrow></math>. </div>
 </PopQuizItem>
 </PopQuiz>
     </div>
<div className="text textcolor">We can refer to individual elements, row, and columns of a matrix using subscripts:</div>
<ul>
<li><div className="text textcolor"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>X</mi><mrow><mi>i</mi><mi>j</mi></mrow></msub></mrow></math> refers to the <span className="term">element</span> of matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi></mrow></math> at row <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>i</mi></mrow></math> and column <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>j</mi></mrow></math>. </div>
</li>
<li><div className="text textcolor"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>X</mi><mrow><mi>i</mi><mo>&#x022C6;</mo></mrow></msub></mrow></math> refers to the <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>i</mi></mrow></math>th <span className="term">row</span> of matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi></mrow></math>, expressed as a vector.</div>
</li>
<li><div className="text textcolor"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>X</mi><mrow><mo>&#x022C6;</mo><mi>j</mi></mrow></msub></mrow></math> refers to the <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>j</mi></mrow></math>th <span className="term">column</span> of matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>X</mi></mrow></math>, expressed as a vector.</div>
</li>
</ul>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> Define: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mi>.2</mi></mtd><mtd><mi>.3</mi></mtd><mtd><mi>.5</mi></mtd></mtr><mtr><mtd><mi>.2</mi></mtd><mtd><mn>0</mn></mtd><mtd><mi>.8</mi></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math></Equation>
 Then: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>A</mi><mrow><mn>11</mn></mrow></msub><mo>&#x0003D;</mo><mi>.2</mi><mo>&#x0002C;</mo><msub><mi>A</mi><mrow><mn>12</mn></mrow></msub><mo>&#x0003D;</mo><mi>.3</mi><mo>&#x0002C;</mo><msub><mi>A</mi><mrow><mn>13</mn></mrow></msub><mo>&#x0003D;</mo><mi>.5</mi></mrow></math></Equation>
 <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>A</mi><mrow><mn>21</mn></mrow></msub><mo>&#x0003D;</mo><mi>.2</mi><mo>&#x0002C;</mo><msub><mi>A</mi><mrow><mn>22</mn></mrow></msub><mo>&#x0003D;</mo><mn>0</mn><mo>&#x0002C;</mo><msub><mi>A</mi><mrow><mn>23</mn></mrow></msub><mo>&#x0003D;</mo><mi>.8</mi></mrow></math></Equation>
 <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>A</mi><mrow><mn>1</mn><mo>&#x022C6;</mo></mrow></msub><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mi>.3</mi></mtd></mtr><mtr><mtd><mi>.5</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mo>&#x0002C;</mo><msub><mi>A</mi><mrow><mn>2</mn><mo>&#x022C6;</mo></mrow></msub><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mn>0</mn></mtd></mtr><mtr><mtd><mi>.8</mi></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math></Equation>
 <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>A</mi><mrow><mo>&#x022C6;</mo><mn>1</mn></mrow></msub><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mi>.2</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mo>&#x0002C;</mo><msub><mi>A</mi><mrow><mo>&#x022C6;</mo><mn>2</mn></mrow></msub><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.3</mi></mtd></mtr><mtr><mtd><mn>0</mn></mtd></mtr></mtable><mo>&#x00029;</mo><mo>&#x0002C;</mo><msub><mi>A</mi><mrow><mo>&#x022C6;</mo><mn>3</mn></mrow></msub><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.5</mi></mtd></mtr><mtr><mtd><mi>.8</mi></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math></Equation>
 </div>
</div>
<div className="text textcolor">For the following questions, let: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>80</mn></mtd><mtd><mn>90</mn></mtd><mtd><mn>96</mn></mtd></mtr><mtr><mtd><mn>95</mn></mtd><mtd><mn>80</mn></mtd><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>90</mn></mtd><mtd><mn>70</mn></mtd><mtd><mn>92</mn></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math></Equation>
</div>
<div className="text textcolor"><PopQuiz>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> For matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>, what is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mn>32</mn></mrow></msub></mrow></math>? </div>
 <div className="pop-answer"> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mn>32</mn></mrow></msub></mrow></math> is the element at row 3 and column 2 of matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>. So <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mn>32</mn></mrow></msub><mo>&#x0003D;</mo><mn>70</mn></mrow></math>. </div>
 </PopQuizItem>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> For matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>, what is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mo>&#x022C6;</mo><mn>2</mn></mrow></msub></mrow></math>? </div>
 <div className="pop-answer"> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mo>&#x022C6;</mo><mn>2</mn></mrow></msub></mrow></math> is the vector corresponding to column 2 of matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>. So: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mo>&#x022C6;</mo><mn>2</mn></mrow></msub><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>80</mn></mtd></mtr><mtr><mtd><mn>70</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math> </div>
 </PopQuizItem>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> For matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>, what is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mn>3</mn><mo>&#x022C6;</mo></mrow></msub></mrow></math>? </div>
 <div className="pop-answer"> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mn>3</mn><mo>&#x022C6;</mo></mrow></msub></mrow></math> is the vector corresponding to row 3 of matrix <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math>. So: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>B</mi><mrow><mn>3</mn><mo>&#x022C6;</mo></mrow></msub><mo>&#x0003D;</mo><mo>&#x00028;</mo><mtable><mtr><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>70</mn></mtd></mtr><mtr><mtd><mn>92</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mrow></math> </div>
 </PopQuizItem>
 </PopQuiz>
     </div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Definition</span><br/><br/> Let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi></mrow></math> be a <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>m</mi><mi>&#x000D7;</mi><mi>n</mi></mrow></math> matrix and let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math> be a <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>n</mi><mi>&#x000D7;</mi><mi>p</mi></mrow></math> matrix. Define <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>C</mi><mo>&#x0003D;</mo><mi>A</mi><mi>B</mi></mrow></math> as the <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>m</mi><mi>&#x000D7;</mi><mi>p</mi></mrow></math> matrix such that: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>C</mi><mrow><mi>i</mi><mi>j</mi></mrow></msub><mo>&#x0003D;</mo><msub><mi>A</mi><mrow><mi>i</mi><mo>&#x022C6;</mo></mrow></msub><mi>&#x000B7;</mi><msub><mi>B</mi><mrow><mo>&#x022C6;</mo><mi>j</mi></mrow></msub></mrow></math></Equation>
 </div>
</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Example</span><br/><br/> Let: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mi>.2</mi></mtd><mtd><mi>.3</mi></mtd><mtd><mi>.5</mi></mtd></mtr><mtr><mtd><mi>.2</mi></mtd><mtd><mn>0</mn></mtd><mtd><mi>.8</mi></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math></Equation>
 <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>80</mn></mtd><mtd><mn>90</mn></mtd><mtd><mn>96</mn></mtd></mtr><mtr><mtd><mn>95</mn></mtd><mtd><mn>80</mn></mtd><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>90</mn></mtd><mtd><mn>70</mn></mtd><mtd><mn>92</mn></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math></Equation>
 Then: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>B</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mi>.3</mi></mtd></mtr><mtr><mtd><mi>.5</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mi>&#x000B7;</mi><mo>&#x00028;</mo><mtable><mtr><mtd><mn>80</mn></mtd></mtr><mtr><mtd><mn>95</mn></mtd></mtr><mtr><mtd><mn>90</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mtd><mtd><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mi>.3</mi></mtd></mtr><mtr><mtd><mi>.5</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mi>&#x000B7;</mi><mo>&#x00028;</mo><mtable><mtr><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>80</mn></mtd></mtr><mtr><mtd><mn>70</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mtd><mtd><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mi>.3</mi></mtd></mtr><mtr><mtd><mi>.5</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mi>&#x000B7;</mi><mo>&#x00028;</mo><mtable><mtr><mtd><mn>96</mn></mtd></mtr><mtr><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>92</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mtd></mtr><mtr><mtd><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mn>0</mn></mtd></mtr><mtr><mtd><mi>.8</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mi>&#x000B7;</mi><mo>&#x00028;</mo><mtable><mtr><mtd><mn>80</mn></mtd></mtr><mtr><mtd><mn>95</mn></mtd></mtr><mtr><mtd><mn>90</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mtd><mtd><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mn>0</mn></mtd></mtr><mtr><mtd><mi>.8</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mi>&#x000B7;</mi><mo>&#x00028;</mo><mtable><mtr><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>80</mn></mtd></mtr><mtr><mtd><mn>70</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mtd><mtd><mo>&#x00028;</mo><mtable><mtr><mtd><mi>.2</mi></mtd></mtr><mtr><mtd><mn>0</mn></mtd></mtr><mtr><mtd><mi>.8</mi></mtd></mtr></mtable><mo>&#x00029;</mo><mi>&#x000B7;</mi><mo>&#x00028;</mo><mtable><mtr><mtd><mn>96</mn></mtd></mtr><mtr><mtd><mn>90</mn></mtd></mtr><mtr><mtd><mn>92</mn></mtd></mtr></mtable><mo>&#x00029;</mo></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math></Equation>
 Which means: <Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>B</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>89.5</mn></mtd><mtd><mn>77</mn></mtd><mtd><mn>92.2</mn></mtd></mtr><mtr><mtd><mn>88</mn></mtd><mtd><mn>74</mn></mtd><mtd><mn>92.8</mn></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math></Equation>
 </div>
</div>
<div className="text textcolor">In the following interactive demo, hovering over an element of the <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>B</mi></mrow></math> matrix will highlight the computation of that element.</div>
<div className="text textcolor"><MatrixMultiplication />
</div>
<div className="text textcolor">For the following questions, let:</div>
<div className="text textcolor"><Equation><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>1</mn></mtd><mtd><mn>2</mn></mtd></mtr><mtr><mtd><mn>3</mn></mtd><mtd><mn>4</mn></mtd></mtr><mtr><mtd><mn>5</mn></mtd><mtd><mn>6</mn></mtd></mtr></mtable><mo>&#x0005D;</mo><mo>&#x0002C;</mo><mi>B</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>6</mn></mtd><mtd><mn>5</mn></mtd><mtd><mn>4</mn></mtd></mtr><mtr><mtd><mn>3</mn></mtd><mtd><mn>2</mn></mtd><mtd><mn>1</mn></mtd></mtr></mtable><mo>&#x0005D;</mo><mo>&#x0002C;</mo><mi>C</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>5</mn></mtd><mtd><mn>1</mn></mtd></mtr><mtr><mtd><mn>10</mn></mtd><mtd><mn>2</mn></mtd></mtr></mtable><mo>&#x0005D;</mo><mo>&#x0002C;</mo></mrow></math></Equation>
</div>
<div className="text textcolor"><PopQuiz>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> What is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>B</mi></mrow></math>? </div>
 <div className="pop-answer"> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>B</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>12</mn></mtd><mtd><mn>9</mn></mtd><mtd><mn>6</mn></mtd></mtr><mtr><mtd><mn>30</mn></mtd><mtd><mn>23</mn></mtd><mtd><mn>16</mn></mtd></mtr><mtr><mtd><mn>48</mn></mtd><mtd><mn>37</mn></mtd><mtd><mn>26</mn></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math>. </div>
 </PopQuizItem>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> What is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mi>A</mi></mrow></math>? </div>
 <div className="pop-answer"> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mi>A</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>41</mn></mtd><mtd><mn>56</mn></mtd></mtr><mtr><mtd><mn>14</mn></mtd><mtd><mn>20</mn></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math>. Note that matrix multiplication is not commutative, i.e. it is not always true that <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>B</mi><mo>&#x0003D;</mo><mi>B</mi><mi>A</mi></mrow></math>. </div>
 </PopQuizItem>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> What is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>C</mi></mrow></math>? </div>
 <div className="pop-answer"> <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>A</mi><mi>C</mi><mo>&#x0003D;</mo><mo>&#x0005B;</mo><mtable><mtr><mtd><mn>25</mn></mtd><mtd><mn>5</mn></mtd></mtr><mtr><mtd><mn>55</mn></mtd><mtd><mn>11</mn></mtd></mtr><mtr><mtd><mn>85</mn></mtd><mtd><mn>17</mn></mtd></mtr></mtable><mo>&#x0005D;</mo></mrow></math>. </div>
 </PopQuizItem>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> What is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mi>C</mi></mrow></math>? </div>
 <div className="pop-answer"> By the definition of matrix multiplication, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math> must be a <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>m</mi><mi>&#x000D7;</mi><mi>n</mi></mrow></math> matrix and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>C</mi></mrow></math> must be a <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>n</mi><mi>&#x000D7;</mi><mi>p</mi></mrow></math> matrix. In other words, the number of columns of <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math> must be equal to the number of rows of <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>C</mi></mrow></math>. However, this is not the case here (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi></mrow></math> has 3 columns and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>C</mi></mrow></math> has 2 rows), so the matrix product <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mi>C</mi></mrow></math> is not defined. </div>
 </PopQuizItem>
 </PopQuiz>
    </div>
<div className="header-padding" /><hr></hr><h4 className="header1" id="derivatives">derivatives</h4>
<div className="text textcolor">This course assumes you have previously taken an introductory calculus course. However it uses calculus notation that, while not original, may be different from the notation that you have previously used.</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Definition</span><br/><br/> Let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi></mrow></math> be a function of variable <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>x</mi></mrow></math>. Define <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00029;</mo></mrow></math> as the first derivative of <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi></mrow></math> with respect to <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>x</mi></mrow></math>. </div>
</div>
<div className="text textcolor">A useful computer sciencey way to think about <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub></mrow></math> is as a function that takes another function <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi></mrow></math> as its argument, and returns a third function (the first derivative of <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi></mrow></math> with respect to <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>x</mi></mrow></math>). </div>
<div className="text textcolor">Assume <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi></mrow></math>, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>g</mi></mrow></math>, and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>h</mi></mrow></math> are all functions of variable <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>x</mi></mrow></math>, and that <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>k</mi></mrow></math> is a constant that doesn't depend on <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>x</mi></mrow></math>. Here are some standard rules for computing derivatives:</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Constant Rule</span><br/><br/> Let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mi>k</mi></mrow></math>. Then <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mn>0</mn></mrow></math>. </div>
</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Power Rule</span><br/><br/> Let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><msup><mi>x</mi><mi>k</mi></msup></mrow></math>. Then <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mi>k</mi><msup><mi>x</mi><mrow><mi>k</mi><mo>&#x02212;</mo><mn>1</mn></mrow></msup></mrow></math>. </div>
</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Sum Rule</span><br/><br/> Let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi><mo>&#x0003D;</mo><mi>g</mi><mo>&#x0002B;</mo><mi>h</mi></mrow></math>. Then <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>g</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0002B;</mo><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>h</mi><mo stretchy="false">&#x00029;</mo></mrow></math>. </div>
</div>
<div className="text textcolor"><div className="definition"><span className="definitionheader">Product Rule</span><br/><br/> Let <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi><mo>&#x0003D;</mo><mi>g</mi><mi>h</mi></mrow></math>. Then <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mi>h</mi><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>g</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0002B;</mo><mi>g</mi><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>h</mi><mo stretchy="false">&#x00029;</mo></mrow></math>. </div>
</div>
<div className="text textcolor">Let's exercise our skills by computing the derivative of <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mn>2</mn><msup><mi>x</mi><mn>3</mn></msup><mo>&#x0002B;</mo><mn>7</mn></mrow></math>.</div>
<div className="text textcolor"><ProofWalkthru marker="="><div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mi>f</mi><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">...</div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mn>2</mn><msup><mi>x</mi><mn>3</mn></msup><mo>&#x0002B;</mo><mn>7</mn><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">by the definition of <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi></mrow></math></div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mrow><msub><mi className="proof-highlight" mathvariant="bold">D</mi><mi className="proof-highlight" mathvariant="bold">x</mi></msub></mrow><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mn>2</mn><msup><mi>x</mi><mn>3</mn></msup><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow><mo>&#x0002B;</mo><mrow><msub><mi className="proof-highlight" mathvariant="bold">D</mi><mi className="proof-highlight" mathvariant="bold">x</mi></msub></mrow><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mn>7</mn><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">sum rule</div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mrow><mn className="proof-highlight" mathvariant="bold">6</mn><msup><mi className="proof-highlight" mathvariant="bold">x</mi><mn className="proof-highlight" mathvariant="bold">2</mn></msup></mrow><mo>&#x0002B;</mo><msub><mi>D</mi><mi>x</mi></msub><mrow><mo stretchy="true" fence="true" form="prefix">&#x00028;</mo><mn>7</mn><mo stretchy="true" fence="true" form="postfix">&#x00029;</mo></mrow></mrow></math></div>
 <div className="justification">power rule</div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>6</mn><msup><mi>x</mi><mn>2</mn></msup><mo>&#x0002B;</mo><mrow><mn className="proof-highlight" mathvariant="bold">0</mn></mrow></mrow></math></div>
 <div className="justification">constant rule</div></div>
 <div className="step"><div className="math"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>6</mn><msup><mi>x</mi><mn>2</mn></msup></mrow></math></div>
 <div className="justification">simplifying</div></div></ProofWalkthru>
</div>
<div className="text textcolor"><PopQuiz>
 <PopQuizItem bullet={bullet}>
 <div className="pop-question"> If <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>f</mi><mo stretchy="false">&#x00028;</mo><mi>x</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><msqrt><mrow><mi>x</mi></mrow></msqrt></mrow></math>, what is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msub><mi>D</mi><mi>x</mi></msub><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00029;</mo></mrow></math>? </div>
 <div className="pop-answer"> Since <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msqrt><mrow><mi>x</mi></mrow></msqrt></mrow></math> can be alternatively expressed as <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><msup><mi>x</mi><mrow><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac></mrow></msup></mrow></math>, we can apply the Power Rule to obtain <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>D</mi><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><msup><mi>x</mi><mrow><mo>&#x02212;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac></mrow></msup></mrow></math>, which can also be expressed as <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>D</mi><mo stretchy="false">&#x00028;</mo><mi>f</mi><mo stretchy="false">&#x00029;</mo><mo>&#x0003D;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn><msqrt><mrow><mi>x</mi></mrow></msqrt></mrow></mfrac></mrow></math>. </div>
 </PopQuizItem>
 </PopQuiz>
     </div>

                        </div>
                    );
                }
    

                export default Chapter1;
                
